[tool.poetry]
name = "kurswork-3-db"
version = "0.1.0"
description = ""
authors = ["Борзунов Андрей <andry73@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
poetry-core = "^2.4.1"
psycopg2-binary = "^2.9.12"
types-psycopg2 = "^2.9.21.20260724"
requests = "^2.34.2"
types-requests = "^2.33.0.20260906"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
mypy = "^2.3.1"
black = "^26.5.1"
isort = "^9.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
exclude = '''
(
    \.git
)
'''

[tool.isort]
line_length = 119

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = 'venv'
